# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CCExtractor
email: contactus@ccextractor.org
description: > # this means to ignore newlines until "baseurl:"
    CCExtractor Development is an informal (meaning we're not incorporated anywhere) organization that exists to coordinate the development efforts of the volunteers that contribute to the   software and to manage our participation in specific events such as Google Summer of Code and Code-In.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ccextractor.github.io" # the base hostname & protocol for your site
twitter_username: ccextractordev
github_username:  CCExtractor
donate: "http://sourceforge.net/donate/index.php?group_id=190832"

# Build settings
markdown: kramdown
